language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

before_script:
  - npm install -g gulp
script: npm run ci

addons:
  sauce_connect:
    username: "iddsfn"
    access_key: "f9230436-fbf8-4eac-96f6-7b136c445382"